### PR TITLE
fix: dummy smtp server

### LINKED ISSUE #401: auth: unencrypted connection
# Bug report
The latest version of the supabase/cli (1.1.1) seems to have a few bugs related to the auth images:

## Describe the bug
- `supabase db start` adds an `ip_address` to the `audit_log_entries` column but the  `supabase db reset` command removes it again. That will result in any auth actions failing
- any `inbucket` related commands in local development will result in this error:

```
"auth_event":{"action":"user_invited","actor_id":"00000000-0000-0000-0000-000000000000","actor_username":"service_role","log_type":"team","traits":{"user_email":"member@example.com","user_id":"010b0e5c-f562-4f4d-b617-dfbd1ada2537"}},"component":"api","error":"Error sending invite email: unencrypted connection","level":"error","method":"POST","msg":"500: Error inviting user","path":"/invite","referer":"","remote_addr":"172.25.0.3:38572","timestamp":"2022-08-22T16:40:08Z"}
```

## To Reproduce
- Make sure you've installed the latest version of the cli (1.1.1)
- Create a new folder
- run `supabase init`
- run `supabase start` and check if you have the `ip_address` column in the auth database
- run `supabae db reset` and check if it's still there
- try sending a password recovery email (or create a new user) through the supabase dashboard

- OS: macOS
- Version of supabase-cli: [1.1.1]

## Extra context
We were coming from supabase cli 0.26.1 which worked. Downgrading to it again (which isn't simple because we're installing through Brew), resolves the issue

### LINKED ISSUE #406: Error Sending Magic Link
# Bug report

## Describe the bug

When running Supabase locally via the CLI, I'm getting the following error when trying to sign in:

```
POST http://localhost:54321/auth/v1/otp

{email: "xxxx@hey.com", create_user: true, gotrue_meta_security: {}}

code: 500
error_id: "79e6a0d2-0398-401d-80cb-6abba937a327"
msg: "Error sending magic link"
```

The user is being correctly created in the `auth.users` table, but nothing is showing up in Inbucket as the error would suggest. 

I'm only getting this error running locally, hence why I posted this issue in this repository.

I know this is hard to decipher with this limited amount of information. Is there some logs hiding somewhere I can look into deeper?

## System information

- OS: macOS
- CLI version: 1.1.2
- Version of supabase-js: 1.35.6
- Version of Node.js: 16.15.0

## Context

I'm signing up like so:

```
await supabaseClient.auth.signIn({
      email: data.email,
    });
```

### PR DESCRIPTION
**Pull request by soedirgo**
Fixes #401, fixes #406

context for workaround: https://github.com/go-gomail/gomail/issues/113

### CODE REVIEW

**Review by sweatybridge — APPROVED** [review]

File: internal/start/start.go [hunk 1]
```diff
@@ -555,7 +555,9 @@ EOF
 
 			"GOTRUE_SMTP_HOST=" + utils.InbucketId,
 			"GOTRUE_SMTP_PORT=2500",
-			"GOTRUE_SMTP_USER=GOTRUE_SMTP_USER",
+			// NOTE: Needs to be empty string to bypass `unencrypted connection` error
+			// See https://github.com/go-gomail/gomail/issues/113
+			"GOTRUE_SMTP_USER=",
 			"GOTRUE_SMTP_PASS=GOTRUE_SMTP_PASS",
```
Comment (sweatybridge) [inline internal/start/start.go:561]: also seems to work if I removed both env var completely

Comment (soedirgo) [reply internal/start/start.go:561]: hmm yeah that seems to work
