### PR TITLE
fix: the container ulimits for reatime

### LINKED ISSUE #2693: Error running `supabase start` storage and realtime ulimit
**Describe the bug**
When running on some linux machine such as fedora I encountered with the "storage" and "realtime" containers an error stoping the containers to start.

```
2024/09/18 09:06:01 Recv First Byte
+ ulimit -n
+ '[' '!' -z 10000 ']'
+ echo 'Setting RLIMIT_NOFILE to 10000'
+ ulimit -Sn 10000
/app/run.sh: line 8: ulimit: open files: cannot modify limit: Invalid argument
```

Workaround for now: disable storage and relatime from the config.toml allow to start the stack locally

**To Reproduce**

On a machine like so: 
```bash
uname -a
Linux fedora 6.10.9-200.fc40.aarch64 #1 SMP PREEMPT_DYNAMIC Sun Sep  8 17:50:45 UTC 2024 aarch64 GNU/Linux
Y
ulimit -a
real-time non-blocking time  (microseconds, -R) unlimited
core file size              (blocks, -c) unlimited
data seg size               (kbytes, -d) unlimited
scheduling priority                 (-e) 0
file size                   (blocks, -f) unlimited
pending signals                     (-i) 31216
max locked memory           (kbytes, -l) 8192
max memory size             (kbytes, -m) unlimited
open files                          (-n) 100000
pipe size                (512 bytes, -p) 8
POSIX message queues         (bytes, -q) 819200
real-time priority                  (-r) 0
stack size                  (kbytes, -s) 8192
cpu time                   (seconds, -t) unlimited
max user processes                  (-u) 31216
virtual memory              (kbytes, -v) unlimited
file locks                          (-x) unlimited
```

Run:

```
supabase start --debug
```

Will result in:

```
Stopped supabase local development setup.
A new version of Supabase CLI is available: v1.192.5 (currently installed v)
We recommend updating regularly for new features and bug fixes: https://supabase.com/docs/guides/cli/getting-started#updating-the-supabase-cli
Supabase CLI 
2024/09/18 09:05:50 Sent Header: Host [api.moby.localhost]
2024/09/18 09:05:50 Sent Header: User-Agent [Docker-Client/unknown-version (linux)]
2024/09/18 09:05:50 Send Done
2024/09/18 09:05:50 Recv First Byte
2024/09/18 09:05:50 Sent Header: Host [api.moby.localhost]
2024/09/18 09:05:50 Sent Header: User-Agent [Docker-Client/unknown-version (linux)]
2024/09/18 09:05:50 Send Done
2024/09/18 09:05:50 Recv First Byte
2024/09/18 09:05:50 Sent Header: Host [api.moby.localhost]
2024/09/18 09:05:50 Sent Header: User-Agent [Docker-Client/unknown-version (linux)]
2024/09/18 09:05:50 Sent Header: Content-Length [296]
2024/09/18 09:05:50 Sent Header: Content-Type [application/json]
2024/09/18 09:05:50 Send Done
2024/09/18 09:05:50 Recv First Byte
2024/09/18 09:05:50 Sent Header: Host [api.moby.localhost]
2024/09/18 09:05:50 Sent Header: User-Agent [Docker-Client/unknown-version (linux)]
2024/09/18 09:05:50 Sent Header: Content-Length [130]
2024/09/18 09:05:50 Sent Header: Content-Type [application/json]
2024/09/18 09:05:50 Send Done
2024/09/18 09:05:50 Recv First Byte
2024/09/18 09:05:50 Sent Header: Host [api.moby.localhost]
2024/09/18 09:05:50 Sent Header: User-Agent [Docker-Client/unknown-version (linux)]
2024/09/18 09:05:50 Sent Header: Content-Length [134]
2024/09/18 09:05:50 Sent Header: Content-Type [application/json]
2024/09/18 09:05:50 Send Done
2024/09/18 09:05:50 Recv First Byte
2024/09/18 09:05:50 Sent Header: Host [api.moby.localhost]
2024/09/18 09:05:50 Sent Header: User-Agent [Docker-Client/unknown-version (linux)]
2024/09/18 09:05:50 Sent Header: Content-Length [12389]
2024/09/18 09:05:50 Sent Header: Content-Type [application/json]
2024/09/18 09:05:50 Send Done
2024/09/18 09:05:50 Recv First Byte
2024/09/18 09:05:50 Sent Header: Host [api.moby.localhost]
2024/09/18 09:05:50 Sent Header: User-Agent [Docker-Client/unknown-version (linux)]
2024/09/18 09:05:50 Sent Header: Content-Length [0]
2024/09/18 09:05:50 Send Done
2024/09/18 09:05:50 Recv First Byte
2024/09/18 09:05:50 Sent Header: Host [api.moby.localhost]
2024/09/18 09:05:50 Sent Header: User-Agent [Docker-Client/unknown-version (linux)]
2024/09/18 09:05:50 Send Done
2024/09/18 09:05:50 Recv First Byte
2024/09/18 09:05:51 Sent Header: Host [api.moby.localhost]
2024/09/18 09:05:51 Sent Header: User-Agent [Docker-Client/unknown-version (linux)]
2024/09/18 09:05:51 Send Done
2024/09/18 09:05:51 Recv First Byte
2024/09/18 09:05:52 Sent Header: Host [api.moby.localhost]
2024/09/18 09:05:52 Sent Header: User-Agent [Docker-Client/unknown-version (linux)]
2024/09/18 09:05:52 Send Done
2024/09/18 09:05:52 Recv First Byte
2024/09/18 09:05:53 Sent Header: Host [api.moby.localhost]
2024/09/18 09:05:53 Sent Header: User-Agent [Docker-Client/unknown-version (linux)]
2024/09/18 09:05:53 Send Done
2024/09/18 09:05:53 Recv First Byte
2024/09/18 09:05:54 Sent Header: Host [api.moby.localhost]
2024/09/18 09:05:54 Sent Header: User-Agent [Docker-Client/unknown-version (linux)]
2024/09/18 09:05:54 Send Done
2024/09/18 09:05:55 Recv First Byte
2024/09/18 09:05:56 Sent Header: Host [api.moby.localhost]
2024/09/18 09:05:56 Sent Header: User-Agent [Docker-Client/unknown-version (linux)]
2024/09/18 09:05:56 Send Done
2024/09/18 09:05:56 Recv First Byte
2024/09/18 09:05:57 Sent Header: Host [api.moby.localhost]
2024/09/18 09:05:57 Sent Header: User-Agent [Docker-Client/unknown-version (linux)]
2024/09/18 09:05:57 Send Done
2024/09/18 09:05:57 Recv First Byte
2024/09/18 09:05:58 Sent Header: Host [api.moby.localhost]
2024/09/18 09:05:58 Sent Header: User-Agent [Docker-Client/unknown-version (linux)]
2024/09/18 09:05:58 Send Done
2024/09/18 09:05:58 Recv First Byte
2024/09/18 09:05:59 Sent Header: Host [api.moby.localhost]
2024/09/18 09:05:59 Sent Header: User-Agent [Docker-Client/unknown-version (linux)]
2024/09/18 09:05:59 Send Done
2024/09/18 09:05:59 Recv First Byte
2024/09/18 09:06:00 Sent Header: Host [api.moby.localhost]
2024/09/18 09:06:00 Sent Header: User-Agent [Docker-Client/unknown-version (linux)]
2024/09/18 09:06:00 Send Done
2024/09/18 09:06:00 Recv First Byte
2024/09/18 09:06:01 Sent Header: Host [api.moby.localhost]
2024/09/18 09:06:01 Sent Header: User-Agent [Docker-Client/unknown-version (linux)]
2024/09/18 09:06:01 Send Done
2024/09/18 09:06:01 Recv First Byte
2024/09/18 09:06:01 Connect Start: tcp 127.0.0.1:54322
2024/09/18 09:06:01 Connect Done: tcp 127.0.0.1:54322
2024/09/18 09:06:01 PG Send: {"Type":"StartupMessage","ProtocolVersion":196608,"Parameters":{"database":"postgres","user":"postgres"}}
2024/09/18 09:06:01 PG Recv: {"Type":"AuthenticationSASL","AuthMechanisms":["SCRAM-SHA-256"]}
2024/09/18 09:06:01 PG Send: {"Type":"SASLInitialResponse","AuthMechanism":"SCRAM-SHA-256","Data":"n,,n=,r=w8MtwtbnIAzahBuxaCbH+1uo"}
2024/09/18 09:06:01 PG Recv: {"Type":"AuthenticationSASLContinue","Data":"r=w8MtwtbnIAzahBuxaCbH+1uo3x+NW7H5X8zUtU0BA9+IsnsU,s=lBrQ96iqxg8oMvLfdqG/1w==,i=4096"}
2024/09/18 09:06:01 PG Send: {"Type":"SASLResponse","Data":"c=biws,r=w8MtwtbnIAzahBuxaCbH+1uo3x+NW7H5X8zUtU0BA9+IsnsU,p=3z76U/wHkRHLKxAaY1td2VAnqsDwjeu5LulVyTX8VTU="}
2024/09/18 09:06:01 PG Recv: {"Type":"AuthenticationSASLFinal","Data":"v=AR9v+BEynq7GCsByY2y3H3Bbgq13hiKuvVLOaH6+CEk="}
2024/09/18 09:06:01 PG Recv: {"Type":"AuthenticationOK"}
2024/09/18 09:06:01 PG Recv: {"Type":"ParameterStatus","Name":"application_name","Value":""}
2024/09/18 09:06:01 PG Recv: {"Type":"ParameterStatus","Name":"client_encoding","Value":"UTF8"}
2024/09/18 09:06:01 PG Recv: {"Type":"ParameterStatus","Name":"DateStyle","Value":"ISO, MDY"}
2024/09/18 09:06:01 PG Recv: {"Type":"ParameterStatus","Name":"default_transaction_read_only","Value":"off"}
2024/09/18 09:06:01 PG Recv: {"Type":"ParameterStatus","Name":"in_hot_standby","Value":"off"}
2024/09/18 09:06:01 PG Recv: {"Type":"ParameterStatus","Name":"integer_datetimes","Value":"on"}
2024/09/18 09:06:01 PG Recv: {"Type":"ParameterStatus","Name":"IntervalStyle","Value":"postgres"}
2024/09/18 09:06:01 PG Recv: {"Type":"ParameterStatus","Name":"is_superuser","Value":"off"}
2024/09/18 09:06:01 PG Recv: {"Type":"ParameterStatus","Name":"server_encoding","Value":"UTF8"}
2024/09/18 09:06:01 PG Recv: {"Type":"ParameterStatus","Name":"server_version","Value":"15.1 (Ubuntu 15.1-1.pgdg20.04+1)"}
2024/09/18 09:06:01 PG Recv: {"Type":"ParameterStatus","Name":"session_authorization","Value":"postgres"}
2024/09/18 09:06:01 PG Recv: {"Type":"ParameterStatus","Name":"standard_conforming_strings","Value":"on"}
2024/09/18 09:06:01 PG Recv: {"Type":"ParameterStatus","Name":"TimeZone","Value":"UTC"}
2024/09/18 09:06:01 PG Recv: {"Type":"BackendKeyData","ProcessID":176,"SecretKey":2085733257}
2024/09/18 09:06:01 PG Recv: {"Type":"ReadyForQuery","TxStatus":"I"}
2024/09/18 09:06:01 Sent Header: Host [api.moby.localhost]
2024/09/18 09:06:01 Sent Header: User-Agent [Docker-Client/unknown-version (linux)]
2024/09/18 09:06:01 Send Done
2024/09/18 09:06:01 Recv First Byte
2024/09/18 09:06:01 Sent Header: Host [api.moby.localhost]
2024/09/18 09:06:01 Sent Header: User-Agent [Docker-Client/unknown-version (linux)]
2024/09/18 09:06:01 Sent Header: Content-Length [296]
2024/09/18 09:06:01 Sent Header: Content-Type [application/json]
2024/09/18 09:06:01 Send Done
2024/09/18 09:06:01 Recv First Byte
2024/09/18 09:06:01 Sent Header: Host [api.moby.localhost]
2024/09/18 09:06:01 Sent Header: User-Agent [Docker-Client/unknown-version (linux)]
2024/09/18 09:06:01 Sent Header: Content-Length [2389]
2024/09/18 09:06:01 Sent Header: Content-Type [application/json]
2024/09/18 09:06:01 Send Done
2024/09/18 09:06:01 Recv First Byte
2024/09/18 09:06:01 Sent Header: Host [api.moby.localhost]
2024/09/18 09:06:01 Sent Header: User-Agent [Docker-Client/unknown-version (linux)]
2024/09/18 09:06:01 Sent Header: Content-Length [0]
2024/09/18 09:06:01 Send Done
2024/09/18 09:06:01 Recv First Byte
2024/09/18 09:06:01 Sent Header: Host [api.moby.localhost]
2024/09/18 09:06:01 Sent Header: User-Agent [Docker-Client/unknown-version (linux)]
2024/09/18 09:06:01 Send Done
2024/09/18 09:06:01 Recv First Byte
+ ulimit -n
+ '[' '!' -z 10000 ']'
+ echo 'Setting RLIMIT_NOFILE to 10000'
+ ulimit -Sn 10000
/app/run.sh: line 8: ulimit: open files: cannot modify limit: Invalid argument
2024/09/18 09:06:01 Sent Header: Host [api.moby.localhost]
2024/09/18 09:06:01 Sent Header: User-Agent [Docker-Client/unknown-version (linux)]
2024/09/18 09:06:01 Send Done
2024/09/18 09:06:01 Recv First Byte
2024/09/18 09:06:01 PG Send: {"Type":"Terminate"}
Stopping containers...
Pruned containers: [a280dde4a77f92f30a69331730b0aad259c64f6df1994f72d57507d3efbd345e]
Pruned volumes: [supabase_db_slack-clone supabase_config_slack-clone]
Pruned network: [supabase_network_slack-clone]
```

**Expected behavior**
Container should start whatever the ulimit.

**Screenshots**

**System information**
Rerun the failing command with `--create-ticket` flag.
 - Ticket ID: [e.g. ab1ac733e31e4f928a4d7c8402543712]
 - Version of OS: [e.g. Ubuntu 22.04]
 - Version of CLI: [e.g. v1.60.0]
 - Version of Docker:
 ```
 docker -v
Docker version 24.0.5, build %{shortcommit_cli}
 ```
 - Versions of services:
 ```
   
        SERVICE IMAGE      │      LOCAL       │ LINKED
  ─────────────────────────┼──────────────────┼─────────
    supabase/postgres      │ 15.1.1.78        │ -
    supabase/gotrue        │ v2.158.1         │ -
    postgrest/postgrest    │ v12.2.0          │ -
    supabase/realtime      │ v2.30.34         │ -
    supabase/storage-api   │ v1.10.1          │ -
    supabase/edge-runtime  │ v1.58.3          │ -
    supabase/studio        │ 20240729-ce42139 │ -
    supabase/postgres-meta │ v0.83.2          │ -
    supabase/logflare      │ 1.4.0            │ -
    supabase/supavisor     │ 1.1.56           │ -
```

**Additional context**
I think this might be due to several factors:
1. The fact that the docker version is a bit behind ?
2. The fact that dealing with `ulimit` in a containerized environment is a bit tricky.
3. Maybe something about the "docker" containers child processes not being spawed in the same environment and having differents `ulimit` than the running users 🤔 

Edit:

Digging a bit more, it seems indeed to be due to a difference between the "docker daemon" `ulimit` and the user `ulimit` indeed, whatever the user might configure as his `ulimit` the docker daemon doesn't necessarily abide to it:

```bash
avallete@fedora:~/cli$ docker run --rm debian sh -c "ulimit -a"
time(seconds)        unlimited
file(blocks)         unlimited
data(kbytes)         unlimited
stack(kbytes)        8192
coredump(blocks)     unlimited
memory(kbytes)       unlimited
locked memory(kbytes) 8192
process              unlimited
nofiles              1024
vmemory(kbytes)      unlimited
locks                unlimited
rtprio               0
avallete@fedora:~/cli$ docker run --ulimit nofile=10000 --rm debian sh -c "ulimit -a"
time(seconds)        unlimited
file(blocks)         unlimited
data(kbytes)         unlimited
stack(kbytes)        8192
coredump(blocks)     unlimited
memory(kbytes)       unlimited
locked memory(kbytes) 8192
process              unlimited
nofiles              10000
vmemory(kbytes)      unlimited
locks                unlimited
rtprio               0
avallete@fedora:~/cli$ docker run --rm debian sh -c "ulimit -a && ulimit -Sn 10000"
sh: 1: ulimit: error setting limit (Invalid argument)
time(seconds)        unlimited
file(blocks)         unlimited
data(kbytes)         unlimited
stack(kbytes)        8192
coredump(blocks)     unlimited
memory(kbytes)       unlimited
locked memory(kbytes) 8192
process              unlimited
nofiles              1024
vmemory(kbytes)      unlimited
locks                unlimited
rtprio               0
avallete@fedora:~/cli$ docker run --ulimit nofile=10000 --rm debian sh -c "ulimit -a && ulimit -Sn 10000"
time(seconds)        unlimited
file(blocks)         unlimited
data(kbytes)         unlimited
stack(kbytes)        8192
coredump(blocks)     unlimited
memory(kbytes)       unlimited
locked memory(kbytes) 8192
process              unlimited
nofiles              10000
vmemory(kbytes)      unlimited
locks                unlimited
rtprio               0
avallete@fedora:~/cli$ ulimit -a
real-time non-blocking time  (microseconds, -R) unlimited
core file size              (blocks, -c) unlimited
data seg size               (kbytes, -d) unlimited
scheduling priority                 (-e) 0
file size                   (blocks, -f) unlimited
pending signals                     (-i) 31216
max locked memory           (kbytes, -l) 8192
max memory size             (kbytes, -m) unlimited
open files                          (-n) 100000
pipe size                (512 bytes, -p) 8
POSIX message queues         (bytes, -q) 819200
real-time priority                  (-r) 0
stack size                  (kbytes, -s) 8192
cpu time                   (seconds, -t) unlimited
max user processes                  (-u) 31216
virtual memory              (kbytes, -v) unlimited
file locks                          (-x) unlimited
```

This limit can be lifted using the docker run option `--ulimit` as mentioned here: https://docs.docker.com/reference/cli/docker/container/run/#ulimit

I think we might want to configure similar behavior as `HostOption` for containers that will attempt to set a specific `ulimit` at runtime.

### PR DESCRIPTION
**Pull request by avallete**
## What kind of change does this PR introduce?

Remove the plain RLIMIT_NOFILE values to ensure it won't be greater than the host system.

Fixes #2693 

## Additional context

### CODE REVIEW

File: internal/utils/docker.go [hunk 1]
```diff
@@ -263,6 +281,15 @@ func DockerStart(ctx context.Context, config container.Config, hostConfig contai
...
 	hostConfig.ExtraHosts = append(hostConfig.ExtraHosts, extraHosts...)
+	// For containers with required NOFILE limit environment ensure
+	// the container ulimit is a match
+	for _, env := range config.Env {
+		if ulimit := getUlimitFromEnvRlimit(env); ulimit != nil {
+			hostConfig.Resources.Ulimits = append(hostConfig.Resources.Ulimits, ulimit)
+			break
+		}
+	}
+
```
Comment (avallete) [inline internal/utils/docker.go:292]: I’m not entirely convinced that placing this "global docker" configuration here is the best approach, as the actual issue lies only with the realtime container. The problem I encountered is that `db start` and `start` run the realtime container in slightly different ways—one allows for the injection of `hostConfig`, while the other does not.

Since this issue could theoretically occur with any container, I thought it might make sense to implement the logic globally. However, if that feels too risky, I can limit the change to the realtime container and refactor the `db start` process to support injecting `hostConfig` with the appropriate resource configuration throughout.

Comment (sweatybridge) [reply internal/utils/docker.go:292]: This env var is specific to realtime and is chosen somewhat arbitrarily https://github.com/supabase/realtime/blob/07a0a1500205c6698994381607064efe0d6ea270/run.sh#L6

How about removing this customisation altogether
- https://github.com/supabase/cli/blob/develop/internal/start/start.go#L762
- https://github.com/supabase/cli/blob/develop/internal/db/start/start.go#L240

**Review by sweatybridge — APPROVED** [review]
