### PR TITLE
fix: update initial schema to include pgsodium

### LINKED ISSUE #383: Error while running db migrations
# Bug report

## Describe the bug

I'm running into the following error when I'm running `supabase db remote commit` or `supabase start` after running the first migration by running `supabase db remote commit`.

```
Error: Error starting shadow database: ERROR:  relation "pgsodium.key_key_id_seq" does not exist
ERROR:  current transaction is aborted, commands ignored until end of transaction block
```

## To Reproduce

1. Create a new Supabase project
2. Install CLI, and link to the project
3. Inside Supabase dashboard, go to SQL editor and run _Stripe subscription starter_ template to create the tables.
4. Run `supabase db remote commit` in the terminal
5. Run `supabase start` or run `supabase db remote commit` again.

## Expected behavior

Run the db migrations without errors

## System information

- OS: macOS
- Version of CLI: 1.0.7

### PR DESCRIPTION
**Pull request by sweatybridge**
## What kind of change does this PR introduce?

fixes #383 

## What is the current behavior?

missing pgsodium schema

## What is the new behavior?

include pgsodium init scripts in upstream image

## Additional context

depends on 
- [x] https://github.com/supabase/postgres/pull/286

### CODE REVIEW

**Comment by soedirgo** [comment]
Getting
```
Error response from daemon: manifest for public.ecr.aws/t3w2s2c9/postgres:14.1.0.66 not found: manifest unknown: Requested image not found
```
There's an extra `v` here: https://github.com/supabase/postgres/blob/615ea0a16b881788a10650991a7cfc086b45c415/.github/workflows/dockerhub-release.yml#L38

File: internal/db/remote/changes/changes.go [hunk 1]
```diff
@@ -170,25 +170,9 @@ EOSQL
...
-			}
-			var errBuf bytes.Buffer
-			if _, err := stdcopy.StdCopy(io.Discard, &errBuf, out); err != nil {
-				return err
-			}
-			if errBuf.Len() > 0 {
-				return errors.New("Error starting shadow database: " + errBuf.String())
-			}
+		p.Send(utils.StatusMsg("Resetting database..."))
+		if err := differ.ResetDatabase(ctx, dbId, utils.ShadowDbName); err != nil {
```
Comment (soedirgo) [inline internal/db/remote/changes/changes.go:174]: Should be `postgres` which is the default `POSTGRES_DB`
```suggestion
		if err := differ.ResetDatabase(ctx, dbId, "postgres"); err != nil {
```
We might also need `PGOPTIONS='--client-min-messages=error` in `reset.sh`

File: internal/db/remote/changes/changes.go [hunk 2]
```diff
@@ -221,7 +205,7 @@ EOSQL
 			}
 
 			out, err := utils.DockerExec(ctx, dbId, []string{
-				"sh", "-c", `PGOPTIONS='--client-min-messages=error' psql postgresql://postgres:postgres@localhost/postgres <<'EOSQL'
+				"sh", "-c", "PGOPTIONS='--client-min-messages=error' psql postgresql://postgres:postgres@localhost/" + utils.ShadowDbName + ` <<'EOSQL'
```
Comment (soedirgo) [inline internal/db/remote/changes/changes.go:208]: Ditto

File: internal/db/remote/changes/changes.go [hunk 3]
```diff
@@ -253,7 +237,7 @@ EOSQL
 				Entrypoint: []string{
 					"sh", "-c", "/venv/bin/python3 -u cli.py --json-diff" +
 						" '" + conn.Config().ConnString() + "'" +
-						" 'postgresql://postgres:postgres@" + dbId + ":5432/postgres'",
+						" 'postgresql://postgres:postgres@" + dbId + ":5432/" + utils.ShadowDbName + "'",
```
Comment (soedirgo) [inline internal/db/remote/changes/changes.go:240]: Ditto

File: internal/db/remote/commit/commit.go [hunk 4]
```diff
@@ -153,8 +153,6 @@ func run(p utils.Program, ctx context.Context, username, password, database stri
 		}
 
 		if len(localMigrations) == 0 {
-			strings.Join(utils.InternalSchemas, "|")
-
```
Comment (soedirgo) [inline internal/db/remote/commit/commit.go:157]: Oops... don't know how this got past the lints

File: internal/db/remote/commit/commit.go [hunk 5]
```diff
@@ -246,25 +244,9 @@ EOSQL
...
-			}
-			var errBuf bytes.Buffer
-			if _, err := stdcopy.StdCopy(io.Discard, &errBuf, out); err != nil {
-				return err
-			}
-			if errBuf.Len() > 0 {
-				return errors.New("Error starting shadow database: " + errBuf.String())
-			}
+		p.Send(utils.StatusMsg("Resetting database..."))
+		if err := differ.ResetDatabase(ctx, dbId, utils.ShadowDbName); err != nil {
```
Comment (soedirgo) [inline internal/db/remote/commit/commit.go:248]: Ditto

File: internal/db/remote/commit/commit.go [hunk 6]
```diff
@@ -294,7 +276,7 @@ EOSQL
 			}
 
 			out, err := utils.DockerExec(ctx, dbId, []string{
-				"sh", "-c", `PGOPTIONS='--client-min-messages=error' psql postgresql://postgres:postgres@localhost/postgres <<'EOSQL'
+				"sh", "-c", "PGOPTIONS='--client-min-messages=error' psql postgresql://postgres:postgres@localhost/" + utils.ShadowDbName + ` <<'EOSQL'
```
Comment (soedirgo) [inline internal/db/remote/commit/commit.go:279]: Ditto

File: internal/db/remote/commit/commit.go [hunk 7]
```diff
@@ -326,7 +308,7 @@ EOSQL
 				Entrypoint: []string{
 					"sh", "-c", "/venv/bin/python3 -u cli.py --json-diff" +
 						" '" + conn.Config().ConnString() + "'" +
-						" 'postgresql://postgres:postgres@" + dbId + ":5432/postgres'",
+						" 'postgresql://postgres:postgres@" + dbId + ":5432/" + utils.ShadowDbName + "'",
```
Comment (soedirgo) [inline internal/db/remote/commit/commit.go:311]: Ditto

File: internal/utils/templates/globals.sql [hunk 8]
```diff
@@ -55,7 +53,7 @@ ALTER ROLE authenticated SET statement_timeout TO '8s';
 -- User Config "authenticator"
 --
 
-ALTER ROLE authenticator SET session_preload_libraries TO 'supautils', 'safeupdate';
```
Comment (soedirgo) [inline internal/utils/templates/globals.sql:58]: Any reason to change this?

File: internal/utils/templates/initial_schemas/14.sql [hunk 9]
```diff
@@ -348,6 +394,7 @@ BEGIN
 
     IF func_is_graphql_resolve
     THEN
+        DROP FUNCTION IF EXISTS graphql_public.graphql;
```
Comment (soedirgo) [inline internal/utils/templates/initial_schemas/14.sql:397]: Where's this line coming from? This function hasn't changed since.

File: internal/db/remote/commit/templates/dump_initial_migration.sh [hunk 10]
```diff
@@ -1,13 +1,17 @@
...
+#   --extension '*'   prevents event triggers from being dumped, bash escaped with single quote
 pg_dump \
     --schema-only \
     --quote-all-identifier \
     --exclude-schema "$EXCLUDED_SCHEMAS" \
-    --schema '*' \
     --extension '*' \
+    --no-comments \
     --dbname "$DB_URL" \
-| sed 's/CREATE SCHEMA "public"/-- CREATE SCHEMA "public"/' \
```
Comment (soedirgo) [inline internal/db/remote/commit/templates/dump_initial_migration.sh:11]: We shouldn't remove this - the `public` schema already exists.

File: internal/db/remote/commit/templates/dump_initial_migration.sh [hunk 11]
```diff
@@ -1,13 +1,17 @@
...
+#   --exclude-schema  omit internal schemas as they are maintained by platform
+#   --no-comments     only object owner can set comment, omit to allow restore by non-superuser
+#   --extension '*'   prevents event triggers from being dumped, bash escaped with single quote
 pg_dump \
     --schema-only \
     --quote-all-identifier \
     --exclude-schema "$EXCLUDED_SCHEMAS" \
-    --schema '*' \
     --extension '*' \
+    --no-comments \
```
Comment (soedirgo) [inline internal/db/remote/commit/templates/dump_initial_migration.sh:15]: We shouldn't omit *all* comments, only those on extensions. `postgres` can't comment on extensions (since they're created by `supabase_admin`), so we assume extension comments are unchanged.

File: internal/db/remote/changes/changes.go (hunk 1 above)
Comment (sweatybridge) [reply internal/db/remote/changes/changes.go:174]: > Should be postgres which is the default POSTGRES_DB

This is a new change introduced in `14.1.0.66`: [docker entrypoint](https://github.com/supabase/postgres/blob/develop/ansible/playbook-docker.yml#L21) now creates additional roles and schemas in default `postgres` db. Our initial schema tries to create the same schema and fails. Hence, we use shadow db. Also, this change makes remote diff consistent with local diff.

File: internal/utils/templates/globals.sql (hunk 8 above)
Comment (sweatybridge) [reply internal/utils/templates/globals.sql:58]: Yes, `supautils` extension is not installed on docker image. So this errors at runtime (more noticeable in self hosted setup).

File: internal/utils/templates/initial_schemas/14.sql (hunk 9 above)
Comment (sweatybridge) [reply internal/utils/templates/initial_schemas/14.sql:397]: It's coming from here https://github.com/supabase/infrastructure/pull/9042. I found this issue by running all infra migration scripts in self hosted docker.

File: internal/db/remote/commit/templates/dump_initial_migration.sh (hunk 10 above)
Comment (sweatybridge) [reply internal/db/remote/commit/templates/dump_initial_migration.sh:11]: I just checked that `create schema "public"` statement is no longer dumped since the removal of `--schema '*'` flag.

File: internal/db/remote/commit/templates/dump_initial_migration.sh (hunk 11 above)
Comment (sweatybridge) [reply internal/db/remote/commit/templates/dump_initial_migration.sh:15]: This is explained in comments of `dump_initial_migration.sh`. Only object owner can set comment. So any object owned by `supabase_admin` will need to be commented. Leaving it there is a time bomb as infra creates more migration scripts in the future.

File: internal/utils/templates/globals.sql (hunk 8 above)
Comment (soedirgo) [reply internal/utils/templates/globals.sql:58]: Note that we need `supautils` in docker eventually, when we move to [extension custom scripts](https://github.com/supabase/supautils/pull/26).

Comment (sweatybridge) [reply internal/utils/templates/globals.sql:58]: Hopefully we will have centralised migrations by then :)

File: internal/db/remote/commit/templates/dump_initial_migration.sh (hunk 11 above)
Comment (soedirgo) [reply internal/db/remote/commit/templates/dump_initial_migration.sh:15]: Sure, but that also removes all comments from users' objects. Anyway, aren't internal schemas supposed to be excluded in the first place?

Comment (sweatybridge) [reply internal/db/remote/commit/templates/dump_initial_migration.sh:15]: I think it's a trade off between getting complaints when cli users fail to `db push` vs complaints when user's object comments are not synced. The latter is less severe and would be my preference.

Perhaps we can add it back when we finally switch sql editor to postgres role.

**Review by soedirgo — APPROVED** [review]
