### PR TITLE
fix: consistently check for migration file when db push

### LINKED ISSUE #625: Only apply migrations with .sql extension
# Bug report

```
❯ npx supabase db push --debug
Enter your database password:
2022/11/21 01:21:41 Connect Start: udp 8.8.8.8:53
2022/11/21 01:21:41 Connect Start: udp 8.8.8.8:53
2022/11/21 01:21:41 Connect Done: udp 8.8.8.8:53
2022/11/21 01:21:41 Connect Done: udp 8.8.8.8:53
[...]
2022/11/21 01:21:41 PG Recv: {"Type":"ReadyForQuery","TxStatus":"I"}
2022/11/21 01:21:41 PG Send: {"Type":"Query","String":"SELECT version FROM supabase_migrations.schema_migrations ORDER BY version"}
2022/11/21 01:21:41 PG Recv: {"Type":"RowDescription","Fields":[{"Name":"version","TableOID":17112,"TableAttributeNumber":1,"DataTypeOID":25,"DataTypeSize":-1,"TypeModifier":-1,"Format":0}]}
2022/11/21 01:21:41 PG Recv: {"Type":"CommandComplete","CommandTag":"SELECT 0"}
2022/11/21 01:21:41 PG Recv: {"Type":"ReadyForQuery","TxStatus":"I"}
Applying unapplied migrations...
Error: Can't process file in supabase/migrations: .DS_Store
```

## Describe the bug

When i run `supabase db push --debug` it will fail due to `.DS_Store` file, which by the way **does not exist** inside `./supabase/migrations/` !!

## To Reproduce

Run `supabase db push --debug` on a mac with an existing sql migration file.

## Expected behavior

It will sync up my migrations to the remote db.

## System information

- OS: macOS 13.0
- Version of supabase: 1.14.3
- Version of Node.js: v16.16.0

### PR DESCRIPTION
**Pull request by sweatybridge**
## What kind of change does this PR introduce?

Bug fix #625

## What is the current behavior?

Please link any relevant issues here.

## What is the new behavior?

- unifies methods to load remote and local migrations
- use batch exec instead of string exec
- add test coverage for db push

## Additional context

Add any other context or screenshots.

### CODE REVIEW

File: internal/db/diff/diff.go [hunk 1]
```diff
@@ -161,17 +160,6 @@ EOSQL
 	return nil
 }
 
-// Creates a fresh database inside a Postgres container.
-func ResetDatabase(ctx context.Context, container, shadow string) error {
```
Comment (sweatybridge) [inline internal/db/diff/diff.go:165]: moved to commit.go

**Review by soedirgo — APPROVED** [review]
